version: 2
updates:
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "monthly"
- package-ecosystem: "maven"
  directories:
  - "/"
  - "/graylog-api"
  - "/graylog-archiving-plugin"
  schedule:
    interval: "monthly"
  open-pull-requests-limit: 20
