version: 2
updates:
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "monthly"
- package-ecosystem: "maven"
  directories:
  - "/"
  - "/graylog-api"
  - "/graylog-archiving-plugin"
  schedule:
    interval: "monthly"
  groups:
    patch:
      applies-to: version-updates
      update-types:
      - patch
    minor:
      applies-to: version-updates
      update-types:
      - minor
    major:
      applies-to: version-updates
      update-types:
      - major
  open-pull-requests-limit: 20
